package com.example.test.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing an in-app notification message
 * Used to store and manage alerts like budget thresholds and system messages
 */
@Entity(tableName = "notifications")
data class Notification(
    /**
     * Unique identifier for the notification, auto-generated by Room
     */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    
    /**
     * The headline or subject of the notification
     */
    val title: String,
    
    /**
     * The detailed content of the notification
     */
    val message: String,
    
    /**
     * Date when the notification was created in string format
     */
    val date: String,
    
    /**
     * Flag indicating whether the user has viewed this notification
     */
    val read: Boolean = false
)

