package com.example.test.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing a financial transaction in the application
 * Transactions can be expenses, income, or transfers between accounts
 */
@Entity(tableName = "transactions")
data class Transaction(
    /**
     * Unique identifier for the transaction, auto-generated by Room
     */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    
    /**
     * Type of transaction: "expense", "income", or "transfer"
     */
    val type: String, // "expense", "income", "transfer"
    
    /**
     * Reference to the category ID, can be null for transfers
     */
    val categoryId: Int?, // can be null for transfers
    
    /**
     * Monetary amount of the transaction
     */
    val amount: Double,
    
    /**
     * Date of the transaction in string format
     */
    val date: String,
    
    /**
     * Account ID from which the money is taken
     */
    val fromAccountId: Int?,
    
    /**
     * Account ID to which the money is deposited (used only for transfers)
     */
    val toAccountId: Int?, // only for transfer
    
    /**
     * Optional descriptive note for the transaction
     */
    val note: String
)
